import typing

import torch

from engine.records import WorkItem


class ModelRunner(typing.Protocol):
    def prefill(self, input_ids: list[torch.Tensor], slots: list[int]) -> torch.Tensor: ...
    def decode(self, tokens: torch.Tensor, slots: torch.Tensor) -> torch.Tensor: ...
    def warmup(self): ...

class Batcher(typing.Protocol):
    def add(self, items: list[WorkItem]): ...
    def has_work(self) -> bool: ...
    def step(self): ...
    def abort_items(self) -> list[WorkItem]: ...
    def get_num_active(self) -> int: ...
    def warmup(self): ...
