import typing

import torch

from engine.records import WorkItem


class ModelRunner(typing.Protocol):
    def prefill(self) -> torch.Tensor: ...
    def decode(self) -> torch.Tensor: ...
    def warmup(self): ...

class Scheduler(typing.Protocol):
    collect_window: float
    def add(self, items: list[WorkItem]): ...
    def has_work(self) -> bool: ...
    def step(self): ...
    def abort_items(self) -> list[WorkItem]: ...
    def warmup(self): ...
